require("basic")
require("plugins")
require("configs.nvim-treesitter")
require("lualine")
require("configs.lualine")
-- require("mason").setup()
-- require("mason-lspconfig").setup()
require("configs.nvim-cmp")
